# 389. Find the Difference
# Easy
# 4.4K
# 448
# Companies
# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"
 

# Constraints:
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.
class Solution(object):
    def findTheDifference(self, s, t):
        result = 0

        # XOR all characters in both strings
        for char in s + t:
            result ^= ord(char)

        return chr(result)

# Example usage:
solution = Solution()
s1 = "abcd"
t1 = "abcde"
print(solution.findTheDifference(s1, t1))  # Output: "e"

s2 = ""
t2 = "y"
print(solution.findTheDifference(s2, t2))  # Output: "y"

        